version: "3.8"
networks:
  expense_network:
    driver: bridge

volumes:
  db_data:

services:
  mysql:
    build: ./db
    image: muralielavarthi/mysql:2.0.0
    #Go to the ./db folder, find a Dockerfile, and build a custom image from it.
    env_file: .env
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - expense_network

  backend:
    build: ./backend
    image: muralielavarthi/backend:2.0.0
    command: sh -c "sleep 20 && node app.js"
    container_name: backend
    env_file: .env
    networks:
      - expense_network
    depends_on:
      - mysql

  web:
    build: ./web
    image: muralielavarthi/frontend:2.0.0
    container_name: web
    env_file: .env
    networks:
      - expense_network
    ports:
      - "${NGINX_PORT}:80" # Map host port to container port to access application externally.
    depends_on:
      - backend
